# Generated by Django 5.1.1 on 2024-10-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name_plural': 'Ingredients'},
        ),
    ]
