# Generated by Django 5.0.7 on 2024-07-26 10:09

import app.user.custom.validators.validate_image
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date and time when the recipe was published')),
                ('last_edit_date', models.DateTimeField(auto_now=True, verbose_name='Date and time of the recipe last edited')),
                ('text', models.TextField(max_length=10000)),
                ('dish_pic', models.ImageField(blank=True, help_text='Picture of the dish', null=True, upload_to='dish_pics/', validators=[app.user.custom.validators.validate_image.validate_dish_image_size, app.user.custom.validators.validate_image.validate_image_extension, app.user.custom.validators.validate_image.validate_dish_image_dimension], verbose_name='Dish Picture')),
                ('ingredient', models.ManyToManyField(db_index=True, related_name='recipes', to='ingredient.ingredient')),
                ('original_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimx', to='recipe.recipe', verbose_name='Original Recipe')),
            ],
        ),
    ]
