# Generated by Django 4.2.15 on 2024-08-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name_plural': 'Recipes'},
        ),
    ]
