# Generated by Django 5.1.1 on 2024-10-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_remove_recipe_name_recipe_description_recipe_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient_quantity',
            field=models.JSONField(default=dict),
        ),
    ]
