# Generated by Django 5.0.7 on 2024-07-26 10:12

import app.user.custom.validators.validate_image
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nickname', models.CharField(db_index=True, max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[0-9a-zA-Z._-]*$', 'Only alphanumeric characters and the characters . - _ are allowed')])),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('food_critic', models.BooleanField(db_index=True, default=False)),
                ('profile_pic', models.ImageField(blank=True, help_text='Picture used for the profile', null=True, upload_to='profile_pics/', validators=[app.user.custom.validators.validate_image.validate_profile_image_size, app.user.custom.validators.validate_image.validate_image_extension, app.user.custom.validators.validate_image.validate_profile_image_dimension], verbose_name='Profile Picture')),
                ('followed', models.ManyToManyField(editable=False, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('liked_recipes', models.ManyToManyField(editable=False, related_name='likes', to='recipe.recipe')),
                ('recipes_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='recipe.recipe', verbose_name='Recipes created')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
    ]
