# Generated by Django 4.2.15 on 2024-08-26 16:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, error_messages={'unique': 'This email is already used'}, max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='followed',
            field=models.ManyToManyField(blank=True, editable=False, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='liked_recipes',
            field=models.ManyToManyField(blank=True, editable=False, related_name='likes', to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(db_index=True, error_messages={'unique': 'This nickname is already used'}, max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[0-9a-z._-]*$', 'Only alphanumeric characters and the characters . - _ are allowed')], verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='recipes_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='recipe.recipe', verbose_name='Recipes created'),
        ),
    ]
