# Generated by Django 5.1.1 on 2024-10-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_ingredient_quantity'),
        ('user', '0004_remove_customuser_recipes_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='saved_recipes',
            field=models.ManyToManyField(blank=True, editable=False, related_name='saved', to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='liked_recipes',
            field=models.ManyToManyField(blank=True, editable=False, related_name='liked', to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='recipes_created',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='author', to='recipe.recipe', verbose_name='Recipes created'),
        ),
    ]
