# Generated by Django 5.1.1 on 2024-11-04 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_saved_recipes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_ingredients',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(db_index=True, error_messages={'unique': 'This nickname is already used'}, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[0-9a-z._-]*$', 'Only alphanumeric characters and the characters . - _ are allowed')], verbose_name='Nickname'),
        ),
    ]
